version: '3.7'

services:
    postgres:
        image: postgres:latest
        container_name: postgres_container
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: example
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: marcus
        volumes:
            - pgdata:/var/lib/postgresql/data # збереження даних
            # Прибираємо виконання SQL-скриптів звідси
            # - ./app/db:/docker-entrypoint-initdb.d

    nodejs:
        image: node:22-alpine
        container_name: nodejs_container
        ports:
            - '8000:8000'
            - '8001:8001'
        working_dir: /app
        volumes:
            - type: bind
              source: ./app
              target: /app
        depends_on:
            - postgres
        command: sh -c "npm install && npm run dev"

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin_container
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@i.ua
            PGADMIN_DEFAULT_PASSWORD: admin
        depends_on:
            - postgres

    db_setup:
        image: postgres:latest
        container_name: db_setup_container
        depends_on:
            - postgres
        volumes:
            - ./app/db:/app/db
        working_dir: /app/db
        entrypoint: ['sh', './setup.sh']

volumes:
    pgdata:
